language: rust
cache: cargo
rust:
  # Uncomment to enable `stable` when 1.26.0 become stable.
  #- stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email: false
